services:
  client:
    container_name: unit-3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3500:3000
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    stdin_open: true
    tty: true
